### ISSUE TITLE
Finalize clang-format and python style guides

### ISSUE THREAD

**Issue by Matthew-Reynolds** [uwreact/uwreact_robot#56]
# 📚 Meta Issue

We're preparing for widespread active development on this repo, and we should be ready with fully fleshed-out linters and formatters to keep our code clean.

## Tracking

 - [x] #60 Add clang-format config
 - [x] #61 Add yapf config
 - [x] #62 Add clang-tidy config
 - [x] #63 Add pylint config

**Comment by Matthew-Reynolds** [comment]
Converted to meta-issue

**Comment by Matthew-Reynolds** [comment]
Add subtasks completed
